"""add model_used to analysis_metrics

Revision ID: 31578e0882d1
Revises: dc4123eea2b5
Create Date: 2026-06-16 11:00:02.692380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31578e0882d1'
down_revision: Union[str, Sequence[str], None] = 'dc4123eea2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_metrics', sa.Column('model_used', sa.String(), nullable=True))
    op.execute("UPDATE analysis_metrics SET model_used = 'unknown' WHERE model_used IS NULL")
    op.alter_column('analysis_metrics', 'model_used', nullable=False)

    op.alter_column('analysis_metrics', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analysis_metrics', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analysis_metrics', 'openrouter_request_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('analysis_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('analysis_metrics', 'processing_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entry', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('entry', 'analysis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('transcription_metrics', 'transcript_segments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('transcription_metrics', 'transcript_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transcription_metrics', 'processing_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcription_metrics', 'processing_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transcription_metrics', 'transcript_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transcription_metrics', 'transcript_segments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('entry', 'analysis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('entry', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('analysis_metrics', 'processing_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analysis_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('analysis_metrics', 'openrouter_request_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('analysis_metrics', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analysis_metrics', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('analysis_metrics', 'model_used')
    # ### end Alembic commands ###
