"""create entry, transcription_metrics, analysis_metrics

Revision ID: dc4123eea2b5
Revises: 
Create Date: 2026-06-15 11:36:13.299044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc4123eea2b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_mode', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('openrouter_request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcription_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcript_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript_duration_ms', sa.Integer(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription_metrics')
    op.drop_table('analysis_metrics')
    op.drop_table('entry')
    # ### end Alembic commands ###
